### ISSUE TITLE
Integer overflow in the computation of the cube of ties in case of big samples; 

### ISSUE THREAD

**Issue by erzakiev** [erzakiev/frictionless#3]
The tie-adjustment factor $t_{ij}^3$ in the denominator of the formula below for the Friedman's statistic
<img width="954" alt="Screen Shot 2022-12-30 at 20 08 56" src="https://user-images.githubusercontent.com/13952639/210104520-b07ce89c-7b4e-4e80-b829-3269ca5c9b1f.png">
 overflows the `int` format... Observed when, for example, the number of dropouts (i.e. 0 expression) was tied many times in a big sample of $2700$ cells: $2691$ ties cubed is $19486825371$, which is an order of magnitude bigger than the `INT_MAX` value which is +2147483647
<img width="645" alt="Screen Shot 2022-12-30 at 20 15 18" src="https://user-images.githubusercontent.com/13952639/210104956-7d509f1f-9f67-417e-a28a-a1f4c0606b61.png">
<img width="857" alt="Screen Shot 2022-12-30 at 20 03 57" src="https://user-images.githubusercontent.com/13952639/210104790-e4e2dd27-8eb7-4e05-aebd-25855aac1d59.png">

**Comment by erzakiev** [comment]
The obvious solution is to use bigInt library in C++, but this was not an obvious obstacle in the test runs that I had before with smaller sample sizes

**Comment by erzakiev** [comment]
Changed the type to `unsigned long int` of the `accumulatedSum` and `tieCounter` variables; should be good for samples of up to 2.6 million cells (see the cube root of the upper limit of this type below):
<img width="252" alt="Screen Shot 2022-12-31 at 08 54 38" src="https://user-images.githubusercontent.com/13952639/210129775-5fa7a8f0-63cf-4702-8ecf-185876f64774.png">

**Comment by jdreo** [comment]
I think the best option would be to use double. Doubles can represent larger numbers, at the expense of precision. In such an overflow case, it would loose less significant digits, but would not wrap around zero, as integers do.

**Comment by erzakiev** [comment]
I think i actually (mistakenly) used `double` in the original code and it still overflew... However it is possible that it was coerced to `int` during some arithmetic operations. I'll give it a go with a proper `double` implementation
